---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-kernel-boot
  name: vmi-kernel-boot
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
    firmware:
      kernelBoot:
        cmdline: console=ttyS0
        kernelPath: kernelImage/
        name: containerdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 1Gi
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/hritvi/image-with-kernel:1.0:devel
    name: containerdisk
