---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-sample
  name: vmi-sample
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
    firmware:
      bootloader:
        efi: {}
      kernelboot:
        kernelpath: bla
        initrdpath: bla
        cmdline: bla
    machine:
      type: ""
    resources:
      requests:
        memory: 1Gi
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/alpine-container-disk-demo:devel
    name: containerdisk
